### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by Namoa0** [edoardottt/cariddi#143] opened 2024-03-18 16:06 UTC
I am trying to use the proxy but it does not establish a connection and they do not tunnel.

`echo test.com | cariddi -proxy http://127.0.0.1:8080`

For illustrative purposes, I create a port with netcat. But in tested in multiple ways.

`nc -vvv -l -p 8080`

No connection is established.

`listening on [any] 8080 ...`

Are proxies not implemented?

Thanks you.

**Comment by edoardottt** [comment] 2024-03-18 17:24
Try with a working target

**Comment by Namoa0** [comment] 2024-03-18 17:29
test.com I gave it as an example. Obviously I have tried with target which works. For example: google.com

Same result.

**Comment by Namoa0** [comment] 2024-03-20 12:59
Can you fixed?

**Comment by edoardottt** [comment] 2024-03-20 13:28
Got your point. 

The problem is `SetProxy sets a proxy for the collector. This method overrides the previously used http.Transport if the type of the transport is not http.RoundTripper. The proxy type is determined by the URL scheme. "http" and "socks5" are supported. If the scheme is empty, "http" is assumed.`, but then to skip insecure certificates cariddi uses http.Transport as transport.

I'll go deeper in this issue in the next days, however **PRs are accepted**. If you want you can submit a solution

**Comment by edoardottt** [comment] 2024-03-23 17:51
Hi @Namoa0 , I've applied some changes to the `devel` branch in order to address this issue. You can find it here https://github.com/edoardottt/cariddi/tree/devel

- Commit: https://github.com/edoardottt/cariddi/commit/290dc124c22048dd9ecc879c38978d4fa635f94a

Let me know if everything works for you (proxy ok, proxy not ok, http without TLS certificate crawled with proxy and without a proxy).

Sorry for my quick and maybe aggressive response `Try with a working target`, I wasn't getting your point...Sorry :/

If you need help or you have some doubts with the tests I'm here to provide assistance : )

**Comment by edoardottt** [comment] 2024-04-01 09:11
Partially fixed in version 1.3.3.

Many targets work fine with new proxy settings, however there could be problems in certain types of target. 
e.g.:
- `https://www.google.com/` works fine with a proxy
- `https://edoardoottavianelli.it/` doesn't work with a proxy. I guess the problem lies within GitHub Pages hosting / Certificates / DNS Resolving.

Before this fix there was a clear problem with proxies, no target was working. 
After this fix a lot of targets can be crawled using a proxy.

If anyone has a better solution I'm all ears, just open an Issue / Pull Request

**Closed by edoardottt** 2024-04-01 09:11 UTC
Labels: bug, help wanted, Go
